language: node_js
node_js:
  - "16.15.1"

# S: Build Lifecycle
install:
  - yarn


script:
  - travis_wait 30 yarn generate

after_script:
  - mv -f README.md dist
  - git clone "https://${GH_TOKEN}@${GHIO_REF}" demo
  - rm -rf demo/assets
  - rm -rf demo/articles
  - rm -rf demo/algorithm
  - cp -R dist/* demo/
  - cd ./demo
  - git config user.name "stonehank"
  - git config user.email "stonehank310@gmail.com"gi
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GHIO_REF}" master:master >/dev/null 2>&1

# E: Build LifeCycle

branches:
  only:
    - main
env:
  global:
     - GHIO_REF: github.com/stonehank/stonehank.github.io
